export const SET_INITIAL_STATE = 'SET_INITIAL_STATE';

export const SET_CONTENT_BODY = 'SET_CONTENT_BODY';
export const SET_NOTIFICATION = 'SET_NOTIFICATION';

export const LOGIN_REQUESTED = 'LOGIN_REQUESTED';
export const LOGIN_SUCCEEDED = 'LOGIN_SUCCEEDED';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOADING_LOGIN = 'LOADING_LOGIN';

export const LOAD_INTEREST = 'LOAD_INTEREST';
export const ADD_INTEREST = 'ADD_INTEREST';
export const EDIT_INTEREST = 'EDIT_INTEREST';
export const REMOVE_INTEREST = 'REMOVE_INTEREST';
export const SUCCEEDED_INTEREST = 'SUCCEEDED_INTEREST';
export const FAILED_INTEREST = 'FAILED_INTEREST';
export const UPDATE_INTEREST = 'UPDATE_INTEREST';
export const LOADING_INTEREST = 'LOADING_INTEREST';
export const RESET_SUCCESS_INTEREST = 'RESET_SUCCESS_INTEREST';
export const ADD_INTEREST_BARTER = 'ADD_INTEREST_BARTER';
export const REMOVE_INTEREST_BARTER = 'REMOVE_INTEREST_BARTER';
export const REMOVE_FORM_INTEREST_BARTER = 'REMOVE_FORM_INTEREST_BARTER';
export const ADD_FORM_INTEREST_BARTER = 'ADD_FORM_INTEREST_BARTER';

export const LOAD_BARTER = 'LOAD_BARTER';
export const ADD_BARTER = 'ADD_BARTER';
export const EDIT_BARTER = 'EDIT_BARTER';
export const REMOVE_BARTER = 'REMOVE_BARTER';
export const LOAD_BARTER_IMAGES = 'LOAD_BARTER_IMAGES';
export const ADD_BARTER_IMAGE = 'ADD_BARTER_IMAGE';
export const REMOVE_BARTER_IMAGE = 'REMOVE_BARTER_IMAGE';
export const SUCCEEDED_BARTER = 'SUCCEEDED_BARTER';
export const UPDATE_BARTER = 'UPDATE_BARTER';
export const UPDATE_BARTER_IMAGES = 'UPDATE_BARTER_IMAGES';
export const SUCCEEDED_ADD_BARTER_IMAGE = 'SUCCEEDED_ADD_BARTER_IMAGE';
export const SUCCEEDED_REMOVE_BARTER_IMAGE = 'SUCCEEDED_REMOVE_BARTER_IMAGE';
export const LOADING_BARTER = 'LOADING_BARTER';
export const RESET_SUCCESS_BARTER = 'RESET_SUCCESS_BARTER';
export const SET_BARTER = 'SET_BARTER';
export const CREATE_BARTER_INTEREST = 'CREATE_BARTER_INTEREST';
export const REMOVE_BARTER_INTEREST = 'REMOVE_BARTER_INTEREST';

export const LOAD_PROPERTY = 'LOAD_PROPERTY';
export const ADD_PROPERTY = 'ADD_PROPERTY';
export const EDIT_PROPERTY = 'EDIT_PROPERTY';
export const REMOVE_PROPERTY = 'REMOVE_PROPERTY';
export const ADD_PROPERTY_GARAGE = 'ADD_PROPERTY_GARAGE';
export const REMOVE_PROPERTY_GARAGE = 'REMOVE_PROPERTY_GARAGE';
export const UPDATE_PROPERTY_IMAGES = 'UPDATE_PROPERTY_IMAGES';
export const SUCCEEDED_ADD_PROPERTY_IMAGE = 'SUCCEEDED_ADD_PROPERTY_IMAGE';
export const SUCCEEDED_REMOVE_PROPERTY_IMAGE = 'SUCCEEDED_REMOVE_PROPERTY_IMAGE';
export const LOAD_PROPERTY_IMAGES = 'LOAD_PROPERTY_IMAGES';
export const ADD_PROPERTY_IMAGE = 'ADD_PROPERTY_IMAGE';
export const REMOVE_PROPERTY_IMAGE = 'REMOVE_PROPERTY_IMAGE';
export const SUCCEEDED_PROPERTY = 'SUCCEEDED_PROPERTY';
export const FAILED_PROPERTY = 'FAILED_PROPERTY';
export const UPDATE_PROPERTY = 'UPDATE_PROPERTY';
export const RESET_LOADING_DATA_PROPERTY = 'RESET_LOADING_DATA_PROPERTY';
export const LOADING_PROPERTY = 'LOADING_PROPERTY';
export const RESET_SUCCESS_PROPERTY = 'RESET_SUCCESS_PROPERTY';

export const CREATE_GARAGE = 'CREATE_GARAGE';
export const REMOVE_GARAGE = 'REMOVE_GARAGE';

export const LOAD_SALES = 'LOAD_SALES';
export const LOAD_SALE = 'LOAD_SALE';
export const ADD_SALE = 'ADD_SALE';
export const EDIT_SALE = 'EDIT_SALE';
export const REMOVE_SALE = 'REMOVE_SALE';
export const SUCCEEDED_SALE = 'SUCCEEDED_SALE';
export const FAILED_SALE = 'FAILED_SALE';
export const UPDATE_SALES = 'UPDATE_SALES';
export const UPDATE_SALE = 'UPDATE_SALE';
export const LOADING_SALE = 'LOADING_SALE';
export const RESET_SUCCESS_SALE = 'RESET_SUCCESS_SALE';
export const UPDATE_FINANCING_SALE = 'UPDATE_FINANCING_SALE';
export const UPDATE_BARTER_PROPERTY_SALE = 'UPDATE_BARTER_PROPERTY_SALE';
export const UPDATE_BARTER_VEHICLE_SALE = 'UPDATE_BARTER_VEHICLE_SALE';

export const LOAD_NEGOTIATION_BY_SALE = 'LOAD_NEGOTIATION_BY_SALE';
export const LOAD_NEGOTIATION_BY_INTEREST = 'LOAD_NEGOTIATION_BY_INTEREST';
export const APPROVE_BY_SELLER = 'APPROVE_BY_SELLER';
export const APPROVE_BY_BUYER = 'APPROVE_BY_BUYER';
export const REPROVE_BY_SELLER = 'REPROVE_BY_SELLER';
export const REPROVE_BY_BUYER = 'REPROVE_BY_BUYER';
export const REMOVE_NEGOTIATION = 'REMOVE_NEGOTIATION';
export const SUCCEEDED_NEGOTIATION = 'SUCCEEDED_NEGOTIATION';
export const FAILED_NEGOTIATION = 'FAILED_NEGOTIATION';
export const UPDATE_SALE_NEGOTIATIONS = 'UPDATE_SALE_NEGOTIATIONS';
export const UPDATE_INTEREST_NEGOTIATIONS = 'UPDATE_INTEREST_NEGOTIATIONS';

export const USER_SUCCEEDED = 'USER_SUCCEEDED';
export const FAILED_USER = 'FAILED_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const LOAD_USER = 'LOAD_USER';
export const ADD_USER = 'ADD_USER';
export const EDIT_USER = 'EDIT_USER';
export const LOADING_USER = 'LOADING_USER';
export const RESET_SUCCESS_USER = 'RESET_SUCCESS_USER';

export const LOAD_NEIGHBORHOODS = 'LOAD_NEIGHBORHOODS';
export const LOAD_NEIGHBORHOOD = 'LOAD_NEIGHBORHOOD';
export const UPDATE_NEIGHBORHOOD = 'UPDATE_NEIGHBORHOOD';
export const UPDATE_NEIGHBORHOODS = 'UPDATE_NEIGHBORHOODS';

export const LOAD_STREET = 'LOAD_STREET';
export const UPDATE_STREET = 'UPDATE_STREET';
