export const SET_INITIAL_STATE = "SET_INITIAL_STATE";

export const LOGIN_REQUESTED = "LOGIN_REQUESTED";
export const LOGIN_SUCCEEDED = "LOGIN_SUCCEEDED";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const INTEREST_SUCCEEDED = "INTEREST_SUCCEEDED";
export const LOAD_INTEREST = "LOAD_INTEREST";
export const SEND_INTEREST = "SEND_INTEREST";
export const UPDATE_INTEREST = "UPDATE_INTEREST";
export const REMOVE_INTEREST = "REMOVE_INTEREST";

export const USER_SUCCEEDED = "USER_SUCCEEDED";
export const LOAD_USER = "LOAD_USER";
export const SEND_USER = "SEND_USER";
export const UPDATE_USER = "UPDATE_USER";
export const CHANGE_USER = "CHANGE_USER";
