export const SET_INITIAL_STATE = 'SET_INITIAL_STATE';

export const LOGIN_REQUESTED = 'LOGIN_REQUESTED';
export const LOGIN_SUCCEEDED = 'LOGIN_SUCCEEDED';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const INTEREST_SUCCEEDED = 'INTEREST_SUCCEEDED';
export const UPDATE_INTEREST = 'UPDATE_INTEREST';
export const LOAD_INTEREST = 'LOAD_INTEREST';
export const ADD_INTEREST = 'ADD_INTEREST';
export const EDIT_INTEREST = 'EDIT_INTEREST';
export const REMOVE_INTEREST = 'REMOVE_INTEREST';
export const LOADING_INTEREST = 'LOADING_INTEREST';
export const RESET_SUCCESS_INTEREST = 'RESET_SUCCESS_INTEREST';
export const ADD_INTEREST_BARTER = 'ADD_INTEREST_BARTER';
export const REMOVE_INTEREST_BARTER = 'REMOVE_INTEREST_BARTER';
export const REMOVE_FORM_INTEREST_BARTER = 'REMOVE_FORM_INTEREST_BARTER';
export const ADD_FORM_INTEREST_BARTER = 'ADD_FORM_INTEREST_BARTER';

export const USER_SUCCEEDED = 'USER_SUCCEEDED';
export const UPDATE_USER = 'UPDATE_USER';
export const LOAD_USER = 'LOAD_USER';
export const ADD_USER = 'ADD_USER';
export const EDIT_USER = 'EDIT_USER';

export const LOAD_NEIGHBORHOODS = 'LOAD_NEIGHBORHOODS';
export const LOAD_NEIGHBORHOOD = 'LOAD_NEIGHBORHOOD';
export const UPDATE_NEIGHBORHOOD = 'UPDATE_NEIGHBORHOOD';
export const UPDATE_NEIGHBORHOODS = 'UPDATE_NEIGHBORHOODS';

export const LOAD_STREET = 'LOAD_STREET';
export const UPDATE_STREET = 'UPDATE_STREET';

export const LOAD_BARTER = 'LOAD_BARTER';
export const ADD_BARTER = 'ADD_BARTER';
export const EDIT_BARTER = 'EDIT_BARTER';
export const REMOVE_BARTER = 'REMOVE_BARTER';
export const SUCCEEDED_BARTER = 'SUCCEEDED_BARTER';
export const UPDATE_BARTER = 'UPDATE_BARTER';
export const CREATE_BARTER_INTEREST = 'CREATE_BARTER_INTEREST';
export const REMOVE_BARTER_INTEREST = 'REMOVE_BARTER_INTEREST';
